### ISSUE TITLE
[BUG] code-server opens blank page when running new version

### ISSUE THREAD

**Issue by yourfavoriteweapon** [linuxserver/docker-code-server#194]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

If I change the repo tolscr.io/linuxserver/code-server:4.96.4-ls254 then it will still work as normal.

However If I leave it was lscr.io/linuxserver/code-server or lscr.io/linuxserver/code-server:latest then when I launch code-server I just get a blank white page.

### Expected Behavior

Code server should run as normal.

### Steps To Reproduce

1. update code-server to newest version
2. try to login

### Environment

```markdown
- OS:Unraid
- How docker service was installed:linuxserver image installed from community app store
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='code-server'
  --net='bridge'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Homebase"
  -e HOST_CONTAINERNAME="code-server"
  -e 'PASSWORD'=
  -e 'HASHED_PASSWORD'=''
  -e 'SUDO_PASSWORD'=''
  -e 'SUDO_PASSWORD_HASH'=''
  -e 'PROXY_DOMAIN'='XXXXXXXX'
  -e 'DEFAULT_WORKSPACE'='/config/workspace'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8443]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/code-server-logo.png'
  -p '8443:8443/tcp'
  -v '/mnt/user/appdata/':'/appdata':'rw'
  -v '/mnt/user/appdata/code-server':'/config':'rw' 'lscr.io/linuxserver/code-server'
9c729252704c8685bb65bcbe4fafaa5bcbb1610c24b26e9637729a6192681885

The command finished successfully!
```

### Container logs

```bash
──────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 4.97.2-ls255
Build-date: 2025-02-18T19:43:23+00:00
───────────────────────────────────────
    
setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
[custom-init] No custom files found, skipping...
[2025-02-19T02:08:57.983Z] info  code-server 4.97.2 34b8d2ed69811c3315a465f01492e9448c9254aa
[2025-02-19T02:08:57.987Z] info  Using user-data-dir /config/data
[2025-02-19T02:08:57.997Z] info  Using config file /config/.config/code-server/config.yaml
[2025-02-19T02:08:57.997Z] info  HTTP server listening on http://0.0.0.0:8443/
[2025-02-19T02:08:57.997Z] info    - Authentication is enabled
[2025-02-19T02:08:57.997Z] info      - Using password from $PASSWORD
[2025-02-19T02:08:57.997Z] info    - Not serving HTTPS
[2025-02-19T02:08:57.997Z] info    - Proxying the following domain:
[2025-02-19T02:08:57.997Z] info      - {{port}}.code.
[2025-02-19T02:08:57.998Z] info  Using proxy URI in PORTS tab: //{{port}}.
[2025-02-19T02:08:57.998Z] info  Session server listening on /config/data/code-server-ipc.sock
[ls.io-init] done.
[20:08:58] 
[20:08:58] Extension host agent started.
```

**Comment by rbrowning85** [comment]
I am experiencing the same issue. Running CodeServer on Unraid.

**Comment by Xelator23** [comment]
Same problem with new update .. using unraid

**Comment by Livefour2day** [comment]
Yes i am also experiencing the same balnk page after password is entered after latest update in unraid

**Comment by crtvrmn** [comment]
can confirm, :latest resulted in a blank white page.
`Linuxserver.io version: 4.97.2-ls255
Build-date: 2025-02-18T19:43:23+00:00

───────────────────────────────────────

   
[custom-init] No custom files found, skipping...
starting with no password
[2025-02-19T09:13:15.001Z] info  code-server 4.97.2 34b8d2ed69811c3315a465f01492e9448c9254aa
[2025-02-19T09:13:15.002Z] info  Using user-data-dir /config/data
[2025-02-19T09:13:15.017Z] info  Using config file /config/.config/code-server/config.yaml
[2025-02-19T09:13:15.017Z] info  HTTP server listening on http://0.0.0.0:8443/
[2025-02-19T09:13:15.017Z] info    - Authentication is disabled
[2025-02-19T09:13:15.017Z] info    - Not serving HTTPS
[2025-02-19T09:13:15.017Z] info  Session server listening on /config/data/code-server-ipc.sock
Connection to 127.0.0.1 8443 port [tcp/*] succeeded!
[ls.io-init] done.
[10:14:05] 
[10:14:05] Extension host agent started.`

switching back to :4.96.4-ls254 works fine again.
`Linuxserver.io version: 4.96.4-ls254
Build-date: 2025-02-15T20:26:18+00:00
───────────────────────────────────────

   
[custom-init] No custom files found, skipping...
starting with no password
[2025-02-19T09:30:18.262Z] info  code-server 4.96.4 b7ef8f9bd70cb5b342fa8ec8a0086bad676d8124
[2025-02-19T09:30:18.264Z] info  Using user-data-dir /config/data
[2025-02-19T09:30:18.279Z] info  Using config file /config/.config/code-server/config.yaml
[2025-02-19T09:30:18.279Z] info  HTTP server listening on http://0.0.0.0:8443/
[2025-02-19T09:30:18.279Z] info    - Authentication is disabled
[2025-02-19T09:30:18.279Z] info    - Not serving HTTPS
[2025-02-19T09:30:18.279Z] info  Session server listening on /config/data/code-server-ipc.sock
Connection to 127.0.0.1 8443 port [tcp/*] succeeded!
[ls.io-init] done.`


i _think_ the first error i saw (but it never came back up again) was something with "version missmatch". but i can not reproduce, nor find the exact error again.

**Comment by ch3p4ll3** [comment]
![Image](https://github.com/user-attachments/assets/5bd26be9-7558-4ba3-b66b-7ebd73808c25)
I think I found the problem, `crypto.randomUUID` method is available only in secure contexts

**Comment by formatBCE** [comment]
Same, docker on Debian Bookworm.

**Comment by scuppasteve** [comment]
Same issue Docker on Unraid.

**Comment by gurupanguji** [comment]
same issue - docker on Unraid

**Comment by pvergezac** [comment]
I confirm same white page error and presence of error in Firefow console about crypto.randomUUID.

![Image](https://github.com/user-attachments/assets/e2eec2a3-b6c4-4015-8f42-529b7b8a0ccc)

**Comment by Roxedus** [comment]
https://github.com/coder/code-server/issues/7212 We will have to wait for a fixed version.

**Comment by dm9tr0** [comment]
Unraid, the same issue.

**Comment by Walkerby** [comment]
Docker, experiencing the same issue

**Comment by benz0li** [comment]
Upstream issue:

* https://github.com/microsoft/vscode/issues/240334

**Comment by gurupanguji** [comment]
Might someone have links on how can one downgrade to the previous docker image release for Unraid?

**Comment by trashken** [comment]
same problem on unraid 7.00

**Comment by j0nnymoe** [comment]
People don't need to keep saying same problem, it's been established it's an upstream issue.

**Comment by corasaniti** [comment]
Same problem here. RaspianOS Bookworm based on Raspberry Pi4 and Pi5
Thanks

**Comment by Livefour2day** [comment]
latest release 4.96.4-ls256 still has not fixed the issue

**Comment by gurues** [comment]
same issue - docker on debian

**Comment by VennBit** [comment]
Can confirm I was seeing this, too.  Once I finished the setup and it was going through the proxy and SSL it started working again.

**Comment by Roxedus** [comment]
No, the fact that the issue is still open should be a good indicator it is not.

**Comment by Hanzzie18** [comment]
Same problem with Vscode on Synology Docker. White screen after login.

**Comment by dm9tr0** [comment]
Of course guys you can continue marking such message as "spam", but it is critical and many users for last 2 weeks have no GUI, just empty page instead of VS code, I have seen that you already released some new version, but it didn`t help.
I absolutely dont understand your priority. 

CRITICAL ISSUE!

**Comment by Roxedus** [comment]
This is not something we can fix. 

1. Vscode merged https://github.com/microsoft/vscode/pull/241690 which needs a release
2. Then coder/code-server pulls in that version into their codebase and does a release
3. At this point we can pick up this release

There is nothing for us to prioritize. Adding a new "same issue" comment makes the comments that actually matters, and explains the situation blend in.

**Comment by dm9tr0** [comment]
I suppose that was fixed and soon will be in release https://github.com/coder/code-server/issues/7245

**Comment by gurupanguji** [comment]
Or just pull the previous version of the image and run that as the container. If you're using the linuxserver docker image, I've written up some instructions here: https://gurupanguji.com/2025/02/21/version-4-9-72-of-code-server-is-no-bueno-switch-to-the-previous-version-to-get-it-working-again/

**Comment by CuddlyCornet645** [comment]
Im on debian 12.9 and im also expiriencing that issue. so what did you guys do to resolve this issue? just install an older version until a update drops that patches this bug? or can i just add a ssl cert and it will work? can someone help?

**Comment by aptalca** [comment]
Either of those options would work.

I have mine reverse proxied with [SWAG](https://github.com/linuxserver/docker-swag) and it works fine.

**Comment by Jeff254** [comment]
> Of course guys you can continue marking such message as "spam", but it is critical and many users for last 2 weeks have no GUI, just empty page instead of VS code, I have seen that you already released some new version, but it didn`t help. I absolutely dont understand your priority.
> 
> CRITICAL ISSUE!

I agree with you. I have had the same issue on UnRaid and it is a tad frustrating. No GUI, can't access and update my configurations. Almost everyday i check for an updaupdate but Nothing. So frustrating..

**Comment by Cyberbeni** [comment]
@Roxedus new VSCode version with the fix has been released: https://github.com/microsoft/vscode/releases/tag/1.98.0

**Comment by MSM74588** [comment]
Experiencing this same issue,
On local network:
```
# Browser Console:
Uncaught TypeError: crypto.randomUUID is undefined
    <anonymous> uuid.ts:13
```

**Comment by Roxedus** [comment]
Step 2 is not done, coder has not pushed a stable release yet. 

It is not fixed upstream quite yet.

**Comment by HelloMihai** [comment]
same issue

this guy was able to get it working it via https https://youtu.be/zQl93hzlbhk?t=328 @ 5:28

**Comment by HelloMihai** [comment]
see my comment above, its flagged as spam

**Comment by Roxedus** [comment]
There is no need to rehash the information thats already in the visible comments. That will be marked as spam, together with "same issue" to keep the comments with useful info visible.

**Comment by Roxedus** [comment]
https://github.com/linuxserver/docker-code-server/releases/tag/4.98.0-ls259 is now built, and showing a UI for me without https.

Thanks for the patience all.
